// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/telegram/v1/tg_session.proto

package telegramv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_telegram_v1_tg_session_proto protoreflect.FileDescriptor

const file_api_telegram_v1_tg_session_proto_rawDesc = "" +
	"\n" +
	" api/telegram/v1/tg_session.proto\x12\vtelegram.v1\x1a\x1eapi/telegram/v1/messages.proto2\xe7\x02\n" +
	"\tTGSession\x12V\n" +
	"\rCreateSession\x12!.telegram.v1.CreateSessionRequest\x1a\".telegram.v1.CreateSessionResponse\x12V\n" +
	"\rDeleteSession\x12!.telegram.v1.DeleteSessionRequest\x1a\".telegram.v1.DeleteSessionResponse\x12P\n" +
	"\vSendMessage\x12\x1f.telegram.v1.SendMessageRequest\x1a .telegram.v1.SendMessageResponse\x12X\n" +
	"\x11SubscribeMessages\x12%.telegram.v1.SubscribeMessagesRequest\x1a\x1a.telegram.v1.MessageUpdate0\x01B+Z)tg-session/pkg/api/telegram/v1;telegramv1b\x06proto3"

var file_api_telegram_v1_tg_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),     // 0: telegram.v1.CreateSessionRequest
	(*DeleteSessionRequest)(nil),     // 1: telegram.v1.DeleteSessionRequest
	(*SendMessageRequest)(nil),       // 2: telegram.v1.SendMessageRequest
	(*SubscribeMessagesRequest)(nil), // 3: telegram.v1.SubscribeMessagesRequest
	(*CreateSessionResponse)(nil),    // 4: telegram.v1.CreateSessionResponse
	(*DeleteSessionResponse)(nil),    // 5: telegram.v1.DeleteSessionResponse
	(*SendMessageResponse)(nil),      // 6: telegram.v1.SendMessageResponse
	(*MessageUpdate)(nil),            // 7: telegram.v1.MessageUpdate
}
var file_api_telegram_v1_tg_session_proto_depIdxs = []int32{
	0, // 0: telegram.v1.TGSession.CreateSession:input_type -> telegram.v1.CreateSessionRequest
	1, // 1: telegram.v1.TGSession.DeleteSession:input_type -> telegram.v1.DeleteSessionRequest
	2, // 2: telegram.v1.TGSession.SendMessage:input_type -> telegram.v1.SendMessageRequest
	3, // 3: telegram.v1.TGSession.SubscribeMessages:input_type -> telegram.v1.SubscribeMessagesRequest
	4, // 4: telegram.v1.TGSession.CreateSession:output_type -> telegram.v1.CreateSessionResponse
	5, // 5: telegram.v1.TGSession.DeleteSession:output_type -> telegram.v1.DeleteSessionResponse
	6, // 6: telegram.v1.TGSession.SendMessage:output_type -> telegram.v1.SendMessageResponse
	7, // 7: telegram.v1.TGSession.SubscribeMessages:output_type -> telegram.v1.MessageUpdate
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_telegram_v1_tg_session_proto_init() }
func file_api_telegram_v1_tg_session_proto_init() {
	if File_api_telegram_v1_tg_session_proto != nil {
		return
	}
	file_api_telegram_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telegram_v1_tg_session_proto_rawDesc), len(file_api_telegram_v1_tg_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_telegram_v1_tg_session_proto_goTypes,
		DependencyIndexes: file_api_telegram_v1_tg_session_proto_depIdxs,
	}.Build()
	File_api_telegram_v1_tg_session_proto = out.File
	file_api_telegram_v1_tg_session_proto_goTypes = nil
	file_api_telegram_v1_tg_session_proto_depIdxs = nil
}
